### PR TITLE
hh

### PR DESCRIPTION
**Pull request by masayyad**
create a new reminder

### CODE REVIEW

**Comment by mahanoor786** [comment]
add any comment

**Comment by mahanoor786** [comment]
adding new comment :

image
new "hello", 'hii'

**Comment by masayyad** [comment]
adding image 
image
follow this
adding link [link](link)

**Comment by mahanoor786** [comment]
adding image 
image
follow this
adding link [link](link)

**Comment by masayyad** [comment]
adding image 
image
follow this
adding link [link](link)

**Comment by mahanoor786** [comment]
adding image 
image

adding image and lot more "more", 'new'

**Pull request merged**
